image:
  repository: backend
  tag: "latest"
  pullPolicy: IfNotPresent
envFrom:
- configMapRef:
    name: backend-config
- secretRef:
    name: backend-mariadb-access
ingress:
  enabled: true
  hosts:
    - host: conference
      paths:
        - "/api"
    - host: conference.backend
      paths:
        - "/"
