grafana:
  sidecar:
    dashboards:
      enabled: true
  ingress:
    enabled: true
    hosts:
      - conference.grafana
    path: /
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: backend-go
        static_configs:
          - targets: ["backend.backend"]
  ingress:
    enabled: true
    hosts:
      - conference.prometheus
    paths:
      - /
    annotations:
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: prometheus-basic-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - Prometheus'
