grafana:
  ingress:
    enabled: true
    hosts:
      - conference.grafana
    path: /
prometheus:
  ingress:
    enabled: true
    hosts:
      - conference.prometheus
    paths:
      - /
    annotations:
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: prometheus-basic-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - Prometheus'
