{
 "title": "Backend Application",
 "description": "Backend GOLang Application",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Talks request time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(backend_GetTalks_sum[2m]))/avg(rate(backend_GetTalks_count[2m]))"
    }
   ]
  },
  {
   "title": "Events request time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(backend_GetEvents_sum[2m]))/avg(rate(backend_GetEvents_count[2m]))"
    }
   ]
  },
  {
   "title": "People request time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(backend_GetPersons_sum[2m]))/avg(rate(backend_GetPersons_count[2m]))"
    }
   ]
  },
  {
   "title": "People talks request time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(backend_GetAllTalksPerPersons_sum[2m]))/avg(rate(backend_GetAllTalksPerPersons_count[2m]))"
    }
   ]
  },
  {
   "title": "Day-overview request time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(backend_GetAllRoomsAtLocations_sum[2m]))/avg(rate(backend_GetAllRoomsAtLocations_count[2m]))"
    }
   ]
  },
  {
   "title": "Update person request time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(backend_UpdatePerson_sum[2m]))/avg(rate(backend_UpdatePerson_count[2m]))"
    }
   ]
  }
 ]
}